-- Registers callbacks for button and IMU tap, signals via BLE send
frame.button.single(function()
    frame.bluetooth.send('\x01')
end)
frame.button.double(function()
    frame.bluetooth.send('\x02')
end)
frame.button.long(function()
    frame.bluetooth.send('\x03')
end)
frame.imu.tap_callback(function()
    frame.bluetooth.send('\x04')
end)
frame.sleep(5.0)
